main:
  - name: Bio
    url: /
    weight: 10
  - name: Research
    url: /#focus
    weight: 11
  - name: Experience
    url: /#experience
    weight: 12
  - name: Papers
    url: /#papers
    weight: 13
  - name: Academic Service
    url: /#service
    weight: 14
  - name: News
    url: /#news
    weight: 15
